<!-- Copyright © Erickson Lopez. MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Auditing\EricksonLopez.Auditing.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Auditing.MySql\EricksonLopez.Auditing.MySql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Auditing.Testing\EricksonLopez.Auditing.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\FakeDb\*.cs" LinkBase="Common\FakeDb" />
  </ItemGroup>

</Project>
